# -*- coding: utf-8 -*-
"""Untitled47.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IkziJSW8ZAbIv2i5NTeuvVZ9vOWfKHAM
"""

!pip install imbalanced-learn xgboost lightgbm lime streamlit

import pandas as pd
import numpy as np
import shap
import joblib

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

from imblearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE

from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.ensemble import RandomForestClassifier
from lime.lime_tabular import LimeTabularExplainer

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("framingham_data.csv")

# Fill missing values
df.fillna(df.median(numeric_only=True), inplace=True)

# Remove weak/noisy feature
if 'education' in df.columns:
    df.drop(columns=['education'], inplace=True)

X = df.drop("TenYearCHD", axis=1)
y = df["TenYearCHD"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

xgb_pipeline = Pipeline([
    ('smote', SMOTE(sampling_strategy=0.5, random_state=42)),
    ('model', XGBClassifier(
        n_estimators=400,
        max_depth=4,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        random_state=42
    ))
])

lgbm_pipeline = Pipeline([
    ('smote', SMOTE(sampling_strategy=0.5, random_state=42)),
    ('model', LGBMClassifier(
        n_estimators=400,
        learning_rate=0.05,
        num_leaves=31,
        random_state=42
    ))
])

rf_pipeline = Pipeline([
    ('smote', SMOTE(sampling_strategy=0.5, random_state=42)),
    ('model', RandomForestClassifier(
        n_estimators=300,
        max_depth=6,
        random_state=42
    ))
])

xgb_pipeline.fit(X_train, y_train)
lgbm_pipeline.fit(X_train, y_train)
rf_pipeline.fit(X_train, y_train)

def evaluate_model(model):
    probs = model.predict_proba(X_test)[:, 1]

    best_thresh = 0.5
    best_acc = 0

    for t in np.arange(0.3, 0.7, 0.01):
        preds = (probs >= t).astype(int)
        acc = accuracy_score(y_test, preds)

        if acc > best_acc:
            best_acc = acc
            best_thresh = t

    final_preds = (probs >= best_thresh).astype(int)

    return [
        best_acc,
        precision_score(y_test, final_preds),
        recall_score(y_test, final_preds),
        f1_score(y_test, final_preds)
    ]

results = []

models = {
    "XGBoost": xgb_pipeline,
    "LightGBM": lgbm_pipeline,
    "Random Forest": rf_pipeline
}

for name, model in models.items():
    acc, prec, rec, f1 = evaluate_model(model)

    results.append([name, acc, prec, rec, f1])

df_results = pd.DataFrame(results, columns=[
    "Model", "Accuracy", "Precision", "Recall", "F1"
])

print(df_results)

from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt

probs = xgb_pipeline.predict_proba(X_test)[:, 1]

fpr, tpr, _ = roc_curve(y_test, probs)
roc_auc = auc(fpr, tpr)

plt.plot(fpr, tpr, label=f"AUC = {roc_auc:.2f}")
plt.plot([0,1],[0,1],'--')

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend()

plt.show()

xgb_model = xgb_pipeline.named_steps['model']

explainer = shap.Explainer(xgb_model)
shap_values = explainer(X_test)

shap.plots.beeswarm(shap_values)

lime_exp = LimeTabularExplainer(
    X_train.values,
    feature_names=X.columns.tolist(),
    class_names=["No", "Yes"],
    mode="classification"
)

exp = lime_exp.explain_instance(
    X_test.iloc[0].values,
    xgb_pipeline.predict_proba
)

exp.show_in_notebook()

clinical = ['sysBP', 'diaBP', 'BMI', 'glucose', 'totChol']
lifestyle = ['currentSmoker', 'cigsPerDay', 'BPMeds', 'diabetes']

def ablation(features):
    model = Pipeline([
        ('smote', SMOTE(sampling_strategy=0.5)),
        ('model', XGBClassifier(n_estimators=300))
    ])

    model.fit(X_train[features], y_train)
    preds = model.predict(X_test[features])

    return accuracy_score(y_test, preds)

print({
    "All Features": ablation(X.columns),
    "Clinical Only": ablation(clinical),
    "Lifestyle Only": ablation(lifestyle),
    "Without Smoking": ablation(X.columns.drop("currentSmoker"))
})

joblib.dump(xgb_pipeline, "model.pkl")
joblib.dump(X.columns.tolist(), "features.pkl")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import joblib
# 
# model = joblib.load("model.pkl")
# 
# st.title("Cardiovascular Disease Risk Predictor")
# 
# st.write("### Fill patient details below")
# 
# # 🔥 Manual inputs (NO LOOP = NO BUGS)
# 
# gender = st.selectbox("Gender", ["Female", "Male"])
# age = st.number_input("Age", 20, 100, 40)
# smoker = st.selectbox("Current Smoker", ["No", "Yes"])
# cigs = st.number_input("Cigarettes per Day", 0, 50, 0)
# bpmeds = st.selectbox("BP Medication", ["No", "Yes"])
# stroke = st.selectbox("Previous Stroke", ["No", "Yes"])
# hypertension = st.selectbox("Hypertension", ["No", "Yes"])
# diabetes = st.selectbox("Diabetes", ["No", "Yes"])
# 
# sysBP = st.number_input("Systolic BP", 80, 250, 120)
# diaBP = st.number_input("Diastolic BP", 50, 150, 80)
# chol = st.number_input("Cholesterol", 100, 400, 200)
# bmi = st.number_input("BMI", 10.0, 50.0, 25.0)
# glucose = st.number_input("Glucose", 50, 400, 100)
# 
# # 🔥 Convert to model format
# data = pd.DataFrame([{
#     "male": 1 if gender == "Male" else 0,
#     "age": age,
#     "currentSmoker": 1 if smoker == "Yes" else 0,
#     "cigsPerDay": cigs,
#     "BPMeds": 1 if bpmeds == "Yes" else 0,
#     "prevalentStroke": 1 if stroke == "Yes" else 0,
#     "prevalentHyp": 1 if hypertension == "Yes" else 0,
#     "diabetes": 1 if diabetes == "Yes" else 0,
#     "sysBP": sysBP,
#     "diaBP": diaBP,
#     "totChol": chol,
#     "BMI": bmi,
#     "glucose": glucose
# }])
# 
# # 🔥 Prediction
# if st.button("Predict"):
#     prob = model.predict_proba(data)[0][1]
# 
#     st.write(f"### Risk Probability: {prob:.2f}")
# 
#     if prob > 0.5:
#         st.error("⚠️ High Risk of Heart Disease")
#     else:
#         st.success("✅ Low Risk")

!pkill -f streamlit
!pkill -f localtunnel

!npm install -g localtunnel

!streamlit run app.py & lt --port 8501

from google.colab import files

files.download("app.py")
files.download("model.pkl")
files.download("features.pkl")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# streamlit
# pandas
# numpy
# scikit-learn
# xgboost
# lightgbm
# imbalanced-learn
# joblib

files.download("requirements.txt")